### ISSUE TITLE
USER STORY: build public restaurant site

### ISSUE THREAD

**Issue by valerieoni** [valerieoni/hearty-dove-restaurant#19]
As a **site owner** I can **have restaurant public site** so that **users can find out more about my restaurant**

### Acceptance Criteria
- no dead links
- site has a landing page
- users can navigate to menu, reservations and contact page

### Tasks
- [x] create skeletal layout for the site
- [x] [add navigation](https://github.com/valerieoni/hearty-dove-restaurant/issues/3)
- [x] wire up the contact form
